/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MembersNewRouteImport } from './routes/members.new'
import { Route as MembersIdEditRouteImport } from './routes/members.$id.edit'
import { Route as MembersIdCardRouteImport } from './routes/members.$id.card'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersNewRoute = MembersNewRouteImport.update({
  id: '/members/new',
  path: '/members/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersIdEditRoute = MembersIdEditRouteImport.update({
  id: '/members/$id/edit',
  path: '/members/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersIdCardRoute = MembersIdCardRouteImport.update({
  id: '/members/$id/card',
  path: '/members/$id/card',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/members/new': typeof MembersNewRoute
  '/members/$id/card': typeof MembersIdCardRoute
  '/members/$id/edit': typeof MembersIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/members/new': typeof MembersNewRoute
  '/members/$id/card': typeof MembersIdCardRoute
  '/members/$id/edit': typeof MembersIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/members/new': typeof MembersNewRoute
  '/members/$id/card': typeof MembersIdCardRoute
  '/members/$id/edit': typeof MembersIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/members/new' | '/members/$id/card' | '/members/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/members/new' | '/members/$id/card' | '/members/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/members/new'
    | '/members/$id/card'
    | '/members/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MembersNewRoute: typeof MembersNewRoute
  MembersIdCardRoute: typeof MembersIdCardRoute
  MembersIdEditRoute: typeof MembersIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/new': {
      id: '/members/new'
      path: '/members/new'
      fullPath: '/members/new'
      preLoaderRoute: typeof MembersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/$id/edit': {
      id: '/members/$id/edit'
      path: '/members/$id/edit'
      fullPath: '/members/$id/edit'
      preLoaderRoute: typeof MembersIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/$id/card': {
      id: '/members/$id/card'
      path: '/members/$id/card'
      fullPath: '/members/$id/card'
      preLoaderRoute: typeof MembersIdCardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MembersNewRoute: MembersNewRoute,
  MembersIdCardRoute: MembersIdCardRoute,
  MembersIdEditRoute: MembersIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
